program ConstrucaoCivil;

uses
  Vcl.Forms,
  Principal in 'Principal.pas' {FormPrincipal},
  Caixa in '..\Modelos\Caixa.pas',
  CaixaMovimentacao in '..\Modelos\CaixaMovimentacao.pas',
  Categoria in '..\Modelos\Categoria.pas',
  ClassificacaoCliente in '..\Modelos\ClassificacaoCliente.pas',
  Contatos in '..\Modelos\Contatos.pas',
  Empresa in '..\Modelos\Empresa.pas',
  Entrada in '..\Modelos\Entrada.pas',
  FormaPagamento in '..\Modelos\FormaPagamento.pas',
  Fornecedores in '..\Modelos\Fornecedores.pas',
  FuncionarioComissao in '..\Modelos\FuncionarioComissao.pas',
  Funcionarios in '..\Modelos\Funcionarios.pas',
  GenericEntidade in '..\Modelos\GenericEntidade.pas',
  ItemEntrada in '..\Modelos\ItemEntrada.pas',
  ItemOrcamento in '..\Modelos\ItemOrcamento.pas',
  ItemPedido in '..\Modelos\ItemPedido.pas',
  ItemSaida in '..\Modelos\ItemSaida.pas',
  Log in '..\Modelos\Log.pas',
  Modulo in '..\Modelos\Modulo.pas',
  Pagamentos in '..\Modelos\Pagamentos.pas',
  Pedido in '..\Modelos\Pedido.pas',
  Pessoa in '..\Modelos\Pessoa.pas',
  PrecoVenda in '..\Modelos\PrecoVenda.pas',
  Produtos in '..\Modelos\Produtos.pas',
  Recebimentos in '..\Modelos\Recebimentos.pas',
  Saida in '..\Modelos\Saida.pas',
  TabelasProdutos in '..\Modelos\TabelasProdutos.pas',
  ItensEntrada in '..\ObjectValues\ItensEntrada.pas',
  ItensPedido in '..\ObjectValues\ItensPedido.pas',
  ItensSaida in '..\ObjectValues\ItensSaida.pas',
  CAtribEntity in '..\Persistencia\CAtribEntity.pas',
  Mapper in '..\Persistencia\Mapper.pas',
  ClientesDAO in '..\Dao\ClientesDAO.pas',
  GenericDAO in '..\Dao\GenericDAO.pas',
  EntidadeFactory in 'Factory\EntidadeFactory.pas',
  Controller in '..\Controller\Controller.pas',
  ControllerCaixaMovimentacao in '..\Controller\ControllerCaixaMovimentacao.pas',
  ControllerClientes in '..\Controller\ControllerClientes.pas',
  ControllerEntrada in '..\Controller\ControllerEntrada.pas',
  ControllerFormaPagamento in '..\Controller\ControllerFormaPagamento.pas',
  ControllerFornecedores in '..\Controller\ControllerFornecedores.pas',
  ControllerFuncionarios in '..\Controller\ControllerFuncionarios.pas',
  ControllerPagamento in '..\Controller\ControllerPagamento.pas',
  ControllerPedido in '..\Controller\ControllerPedido.pas',
  ControllerPermissoes in '..\Controller\ControllerPermissoes.pas',
  ControllerProdutos in '..\Controller\ControllerProdutos.pas',
  ControllerRecebimento in '..\Controller\ControllerRecebimento.pas',
  ControllerTabelas in '..\Controller\ControllerTabelas.pas',
  Baixar in '..\Baixar.pas' {FormBaixar},
  Constantes in '..\Constantes.pas',
  DBUtils in '..\DBUtils.pas',
  DialogsUtils in '..\DialogsUtils.pas',
  FiltroPeriodo in '..\FiltroPeriodo.pas' {Form1},
  LoginAcesso in '..\LoginAcesso.pas' {FormLoginAcesso},
  Parcelar in '..\Parcelar.pas' {FormParcelar},
  TemplateComboEditDialog in '..\TemplateComboEditDialog.pas' {TemplateFormComboboEditDialog},
  TemplateDetalhesBase in '..\TemplateDetalhesBase.pas' {TemplateFormBaseDetalhes},
  TemplateDetalhesComTab in '..\TemplateDetalhesComTab.pas' {TemplateFormComTabDetalhes},
  TemplateDetalhesComTabGrid in '..\TemplateDetalhesComTabGrid.pas' {TemplateFormComTabGridDetalhes},
  TemplateListagemBase in '..\TemplateListagemBase.pas' {TemplateFormListagemBase},
  UtilsNumeros in '..\UtilsNumeros.pas',
  UtilsString in '..\UtilsString.pas',
  Boleto in '..\Views\Boleto\Boleto.pas' {FormBoleto},
  CaixaDetalhes in '..\Views\Caixa\CaixaDetalhes.pas' {FormCaixaDetalhes},
  CaixaFinanceiroDetalhes in '..\Views\Caixa\CaixaFinanceiroDetalhes.pas',
  FiltroFluxoCaixa in '..\Views\Caixa\FiltroFluxoCaixa.pas' {FormFiltroFluxoCaixa},
  RelFluxoCaixa in '..\Views\Caixa\RelFluxoCaixa.pas' {FormRelFluxoCaixa},
  RelMovimentacaoCaixaFinanceiro in '..\Views\Caixa\RelMovimentacaoCaixaFinanceiro.pas' {FormRelMovimentacaoCaixaFinanceiro},
  ClientesDetalhes in '..\Views\Clientes\ClientesDetalhes.pas' {FormClientesDetalhes},
  ContatosClientesListagem in '..\Views\Clientes\ContatosClientesListagem.pas' {FormContatosClientesListagem},
  EmpresaDetalhes in '..\Views\Empresa\EmpresaDetalhes.pas' {FormEmpresaDetalhes},
  EntradaDetalhes in '..\Views\Entradas\EntradaDetalhes.pas' {FormEntradaDetalhes},
  EntradaListagem in '..\Views\Entradas\EntradaListagem.pas' {FormEntradaListagem},
  FornecedoresDetalhes in '..\Views\Fornecedores\FornecedoresDetalhes.pas' {FormFornecedoresDetalhes},
  FuncionariosComboboEditDialog in '..\Views\Funcionarios\FuncionariosComboboEditDialog.pas' {FormFuncionariosComboboEditDialog},
  FuncionariosDetalhes in '..\Views\Funcionarios\FuncionariosDetalhes.pas' {FormFuncionariosDetalhes},
  LogListagem in '..\Views\Log\LogListagem.pas' {FormLogListagem},
  PagamentoDetalhes in '..\Views\Pagamentos\PagamentoDetalhes.pas' {FormPagamentoDetalhes},
  Relpagamento in '..\Views\Pagamentos\Relpagamento.pas' {FormRelPagamento},
  PedidoDetalhes in '..\Views\Pedidos\PedidoDetalhes.pas' {FormPedidoDetalhes},
  PedidoListagem in '..\Views\Pedidos\PedidoListagem.pas' {FormPedidoListagem},
  PermissoesAcessos in '..\Views\Permissoes\PermissoesAcessos.pas' {FormPermissoes},
  ProdutosDetalhes in '..\Views\Produtos\ProdutosDetalhes.pas' {FormProdutosDetalhes},
  RecebimentosDetalhes in '..\Views\Recebimentos\RecebimentosDetalhes.pas' {FormRecebimentoDetalhes},
  RelRecebimento in '..\Views\Recebimentos\RelRecebimento.pas' {FormRelRecebimento},
  SaidaDetalhes in '..\Views\Saidas\SaidaDetalhes.pas' {FormSaidaDetalhes},
  SaidaListagem in '..\Views\Saidas\SaidaListagem.pas' {FormSaidaListagem},
  CategoriasDetalhes in '..\Views\Tabelas\CategoriasDetalhes.pas' {FormCategoriasDetalhes},
  ClassificacaoDetalhes in '..\Views\Tabelas\ClassificacaoDetalhes.pas' {FormClassificacaoDetalhes},
  FamiliaProdutosDetalhes in '..\Views\Tabelas\FamiliaProdutosDetalhes.pas' {FormFamiliaProdutosDetalhes},
  FormaPagamentoDetalhes in '..\Views\Tabelas\FormaPagamentoDetalhes.pas' {FormFormaPagamentoDetalhes},
  GrupoProdutosDetalhes in '..\Views\Tabelas\GrupoProdutosDetalhes.pas' {FormGrupoProdutosDetalhes},
  ParametrosPrecoVendaDetalhes in '..\Views\Tabelas\ParametrosPrecoVendaDetalhes.pas' {FormParametrosPrecoVendaDetalhes},
  SubGrupoProdutosDetalhes in '..\Views\Tabelas\SubGrupoProdutosDetalhes.pas' {FormSubGrupoProdutosDetalhes},
  ControllerSaida in '..\Controller\ControllerSaida.pas',
  srvModBaseDados in 'Conexao\srvModBaseDados.pas' {DSServerModuleBaseDados: TDataModule},
  BoletoACBr in '..\Views\Boleto\BoletoACBr.pas' {frmBoletoACBr},
  ConstrutoraProdutosDetalhes in 'Views\ConstrutoraProdutosDetalhes.pas' {FormConstrutoraProdutosDetalhes},
  EtapaDetalhes in 'Views\EtapaDetalhes.pas' {FormEtapaDetalhes},
  EtapaFase in 'Modelo\EtapaFase.pas',
  FaseDetalhes in 'Views\FaseDetalhes.pas' {FormFaseDetalhes},
  SubFaseDetalhes in 'Views\SubFaseDetalhes.pas' {FormSubFaseDetalhes},
  EquipeDetalhes in 'Views\EquipeDetalhes.pas' {FormEquipeDetalhes},
  Equipe in 'Modelo\Equipe.pas',
  Cargo in '..\Modelos\Cargo.pas',
  CargoDetalhes in '..\Views\Tabelas\CargoDetalhes.pas' {FormCargoDetalhes},
  DiarioAtvidadeDetalhes in 'Views\DiarioAtvidadeDetalhes.pas' {FormDiarioAtividadeDetalhes},
  DiarioAtividade in 'Modelo\DiarioAtividade.pas',
  ItemDiarioAtividade in 'Modelo\ItemDiarioAtividade.pas',
  ImovelUnidade in '..\Imobiliaria\Modelos\ImovelUnidade.pas',
  Imovel in '..\Imobiliaria\Modelos\Imovel.pas',
  ImovelCaracteristica in '..\Imobiliaria\Modelos\ImovelCaracteristica.pas',
  ImovelClassificacao in '..\Imobiliaria\Modelos\ImovelClassificacao.pas',
  ImovelSituacao in '..\Imobiliaria\Modelos\ImovelSituacao.pas',
  ImovelTipo in '..\Imobiliaria\Modelos\ImovelTipo.pas',
  ImovelClassificacaoDetalhes in '..\Imobiliaria\Views\Imovel\ImovelClassificacaoDetalhes.pas' {FormImovelClassificacaoDetalhes},
  ImovelSituacaoDetalhes in '..\Imobiliaria\Views\Imovel\ImovelSituacaoDetalhes.pas' {FormImovelSituacaoDetalhes},
  ImovelTipoDetalhes in '..\Imobiliaria\Views\Imovel\ImovelTipoDetalhes.pas' {FormImovelTipoDetalhes},
  ImovelDetalhes in '..\Imobiliaria\Views\Imovel\ImovelDetalhes.pas' {FormImoveisDetalhes},
  ImovelUnidadeDetalhes in '..\Imobiliaria\Views\Imovel\ImovelUnidadeDetalhes.pas' {FormUnidadeImovelDetalhes},
  RelDiarioObra in 'Views\RelDiarioObra.pas' {FormRelDiarioObra},
  ParametrosPrecoVenda in '..\Modelos\ParametrosPrecoVenda.pas',
  UnidadeMedida in '..\Modelos\UnidadeMedida.pas',
  QuantitativoDetalhes in 'Views\QuantitativoDetalhes.pas' {FormQuantitativoDetalhes},
  Quantitativo in 'Modelo\Quantitativo.pas',
  ItemQuantitativo in 'Modelo\ItemQuantitativo.pas',
  ProjetoDetalhes in 'Views\ProjetoDetalhes.pas' {FormProjetoDetalhes},
  Projeto in 'Modelo\Projeto.pas',
  Vcl.Themes,
  Vcl.Styles,
  RelProducao in 'Views\RelProducao.pas' {FormRelProducao},
  RelProducaoResumido in 'Views\RelProducaoResumido.pas' {FormRelProducaoResumido},
  RelProducaoAcumuladaDetalhada in 'Views\RelProducaoAcumuladaDetalhada.pas' {FormRelProducaoAcumuladaDetalhada},
  ControllerDiarioAtividade in 'Controllers\ControllerDiarioAtividade.pas',
  RelProducaoAcumuladaResumido in 'Views\RelProducaoAcumuladaResumido.pas' {FormRelProducaoAcumuladaResumido},
  RelProducaoAcumuladoPorEquipe in 'Views\RelProducaoAcumuladoPorEquipe.pas' {FormResumoProducaoAmuladoPorEquipe},
  DBCtrlGridNew in '..\Componentes\DBCtrlGridNew.pas',
  MapaObraAgora in 'Views\MapaObraAgora.pas' {FormMapaDaObra},
  RelAcompanhamento in 'Views\RelAcompanhamento.pas' {Form2},
  RelResumoEstatistico in 'Views\RelResumoEstatistico.pas' {FormRelResumoEstatistico},
  RelMapaDaObra in 'Views\RelMapaDaObra.pas' {FormRelMapaDaObra},
  RelRecibo in '..\Views\Recebimentos\RelRecibo.pas' {FormRelRecibo},
  AcompanhamentoDiarioAtvidadeDetalhes in 'Views\AcompanhamentoDiarioAtvidadeDetalhes.pas' {FormAcompanhamentoDiarioAtvidadeDetalhes},
  ControllerOrcamento in '..\Controller\ControllerOrcamento.pas',
  RelRecebimento2 in '..\Views\Recebimentos\RelRecebimento2.pas' {FormRelRecebimento2},
  RelBalancoContabil in '..\Views\Pagamentos\RelBalancoContabil.pas' {FormRelBalancoContabil};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  TStyleManager.TrySetStyle('Emerald Light Slate');
  Application.CreateForm(TFormPrincipal, FormPrincipal);
  Application.CreateForm(TDSServerModuleBaseDados, DSServerModuleBaseDados);
  Application.Run;
end.
