unit TabelaCID;

interface

uses
   Classes, CAtribEntity,  GenericEntidade;

type
  [TableName('TabelaCID')]
  TTabelaCID = class(TGenericEntidade)
  private
    FDescricao: string;
    FCodigo: Integer;
    procedure SetCodigo(const Value: Integer);
    procedure SetDescricao(const Value: string);
  public
    CIDList:TStringList;
    constructor create;
    [KeyField('Codigo')]
    property Codigo: Integer read FCodigo write SetCodigo;
    [FieldName('Descricao')]
    property Descricao: string read FDescricao write SetDescricao;
  end;

implementation

{ TabelaCID }

constructor TTabelaCID.create;
begin
   CIDList:= TstringList.Create;

   CIDList.add('F00 - Demência na doença de Alzheimer');
   CIDList.add('F01 - Demência vascular');
   CIDList.add('F01.1 - Demência por infartos múltiplos');
   CIDList.add('F02 - Demência em outras doenças classificadas em outra parte');
   CIDList.add('F02.0 - Demência da doença de Pick');
   CIDList.add('F02.1 - Demência na doença de Creutzfeldt-Jakob');
   CIDList.add('F02.2 - Demência na doença de Huntington');
   CIDList.add('F02.3 - Demência na doença de Parkinson');
   CIDList.add('F02.4 - Demência na doença pelo vírus da imunodeficiência humana HIV -');
   CIDList.add('F03 - Demência não especificada');
   CIDList.add('F04 - Síndrome amnésica orgânica não induzida pelo álcool ou por outras substâncias psicoativas');
   CIDList.add('F05 - Delirium não induzido pelo álcool ou por outras substâncias psicoativas');
   CIDList.add('F06 - Outros transtornos mentais devidos a lesão e disfunção cerebral e a doença física');
   CIDList.add('F07 - Transtornos de personalidade e do comportamento devidos a doença, a lesão e a disfunção cerebral');
   CIDList.add('F09 - Transtorno mental orgânico ou sintomático não especificado');
   CIDList.add('F10 - Transtornos mentais e comportamentais devidos ao uso de álcool');
   CIDList.add('F11 - Transtornos mentais e comportamentais devidos ao uso de opiáceos');
   CIDList.add('F12 - Transtornos mentais e comportamentais devidos ao uso de canabinóides');
   CIDList.add('F13 - Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos');
   CIDList.add('F14 - Transtornos mentais e comportamentais devidos ao uso da cocaína');
   CIDList.add('F15 - Transtornos mentais e comportamentais devidos ao uso de outros estimulantes, inclusive a cafeína');
   CIDList.add('F16 - Transtornos mentais e comportamentais devidos ao uso de alucinógenos');
   CIDList.add('F17 - Transtornos mentais e comportamentais devidos ao uso de fumo');
   CIDList.add('F18 - Transtornos mentais e comportamentais devidos ao uso de solventes voláteis');
   CIDList.add('F19 - Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e ao uso de outras substâncias psicoativas');
   CIDList.add('F20 - Esquizofrenia');
   CIDList.add('F20.0 - Esquizofrenia paranóide');
   CIDList.add('F20.1 - Esquizofrenia hebefrênica');
   CIDList.add('F20.2 - Esquizofrenia catatônica');
   CIDList.add('F20.3 - Esquizofrenia indiferenciada');
   CIDList.add('F20.4 - Depressão pós-esquizofrênica');
   CIDList.add('F20.5 - Esquizofrenia residual');
   CIDList.add('F20.6 - Esquizofrenia simples');
   CIDList.add('F20.8 - Outras esquizofrenias');
   CIDList.add('F20.9 - Esquizofrenia não especificada');
   CIDList.add('F21 - Transtorno esquizotípico');
   CIDList.add('F22 - Transtornos delirantes persistentes');
   CIDList.add('F22.0 - Transtorno delirante');
   CIDList.add('F23 - Transtornos psicóticos agudos e transitórios');
   CIDList.add('F23.0 - Transtorno psicótico agudo polimorfo, sem sintomas esquizofrênicos');
   CIDList.add('F23.1 - Transtorno psicótico agudo polimorfo, com sintomas esquizofrênicos');
   CIDList.add('F23.2 - Transtorno psicótico agudo de tipo esquizofrênico');
   CIDList.add('F23.3 - Outros transtornos psicóticos agudos, essencialmente delirantes');
   CIDList.add('F23.8 - Outros transtornos psicóticos agudos e transitórios');
   CIDList.add('F23.9 - Transtorno psicótico agudo e transitório não especificado');
   CIDList.add('F24 - Transtorno delirante induzido');
   CIDList.add('F25 - Transtornos esquizoafetivos');
   CIDList.add('F25.0 - Transtorno esquizoafetivo do tipo maníaco');
   CIDList.add('F25.1 - Transtorno esquizoafetivo do tipo depressivo');
   CIDList.add('F25.2 - Transtorno esquizoafetivo do tipo misto');
   CIDList.add('F25.8 - Outros transtornos esquizoafetivos');
   CIDList.add('F25.9 - Transtorno esquizoafetivo não especificado');
   CIDList.add('F28 - Outros transtornos psicóticos não-orgânicos');
   CIDList.add('F29 - Psicose não-orgânica não especificada');
   CIDList.add('F30 - Episódio maníaco');
   CIDList.add('F30.0 - Hipomania');
   CIDList.add('F30.1 - Mania sem sintomas psicóticos');
   CIDList.add('F30.2 - Mania com sintomas psicóticos');
   CIDList.add('F30.8 - Outros episódios maníacos');
   CIDList.add('F30.9 - Episódio maníaco, não especificado');
   CIDList.add('F31 - Transtorno afetivo bipolar');
   CIDList.add('F32 - Episódios depressivos');
   CIDList.add('F32.0 - Episódio depressivo leve');
   CIDList.add('F32.1 - Episódio depressivo moderado');
   CIDList.add('F32.2 - Episódio depressivo grave sem sintomas psicóticos');
   CIDList.add('F32.3 - Episódio depressivo grave Com sintomas psicóticos');
   CIDList.add('F32.8 - Outros episódios depressivos');
   CIDList.add('F32.9 - Episódio depressivo, não especificado');
   CIDList.add('F33 - Transtorno depressivo recorrente');
   CIDList.add('F33.1 - Transtorno depressivo recorrente, episódio  atual moderado');
   CIDList.add('F33.2 - Transtorno depressivo recorrente, episódio atual grave sem sintomas psicóticos');
   CIDList.add('F33.3 - Transtorno depressivo recorrente, episódio atual grave com sintomas psicóticos');
   CIDList.add('F33.4 - Transtorno depressivo recorrente, atualmente em remissão');
   CIDList.add('F33.8 - Outros Transtorno depressivos recorrentes');
   CIDList.add('F33.9 - Transtorno depressivo recorrente, não especificado');
   CIDList.add('F34 - Transtornos de humor [afetivos] persistentes');
   CIDList.add('F34.0 - Ciclotimia');
   CIDList.add('F34.1 - Distimia');
   CIDList.add('F34.8 - Outros Transtornos persistentes do humor (afetivos)');
   CIDList.add('F34.9 - Transtornos persistentes do humor (afetivo), não especificado');
   CIDList.add('F38 - Outros transtornos do humor [afetivos]');
   CIDList.add('F38.1 - Outros transtornos recorrentes do humor (afetivos)');
   CIDList.add('F38.8 - Outros transtornos do humor (afetivos) especificados');
   CIDList.add('F39 - Transtorno do humor [afetivo] não especificado');
   CIDList.add('F40 - Transtornos fóbico-ansiosos');
   CIDList.add('F40.0 - Agorafobia');
   CIDList.add('F40.1 - Fobia social');
   CIDList.add('F40.2 - Fobia específica');
   CIDList.add('F41 - Outros transtornos ansiosos');
   CIDList.add('F41.0 - Transtorno do pânico [ansiedade paroxística episódica]');
   CIDList.add('F41.1 - Transtorno de ansiedade generalizada');
   CIDList.add('F41.2 - Transtorno misto de ansiedade e depressão.');
   CIDList.add('F41.3 - Outros transtornos de ansiedade mistos');
   CIDList.add('F41.8 - Outros transtornos ansiosos especificados');
   CIDList.add('F41.9 - Transtorno ansioso, não especificado');
   CIDList.add('F42 - Transtorno obsessivo-compulsivo');
   CIDList.add('F42.0 - Com predominância de idéias ou de ruminações obsessivas');
   CIDList.add('F42.1 - Com predominância de comportamentos compulsivos (rituais obsessivos)');
   CIDList.add('F42.2 - Forma mista com idéias  obsessivas e comportamentos compulsivos');
   CIDList.add('F42.8 - Outros transtornos obsessivo-compulsivos');
   CIDList.add('F42.9 - Transtorno obsessivo-compulsivo, não especificado');
   CIDList.add('F43 - Reações ao “stress” grave e transtornos de adaptação');
   CIDList.add('F43.0 - Reação aguda ao estresse');
   CIDList.add('F43.1 - Estado de stress pós-traumático');
   CIDList.add('F43.2 - Transtorno de adaptação');
   CIDList.add('F44 - Transtornos dissociativos de conversão -');
   CIDList.add('F44.0 - Amnésia dissociativa');
   CIDList.add('F44.1 - Fuga dissociativa');
   CIDList.add('F44.2 - Estupor dissociativo');
   CIDList.add('F44.3 - Transtornos de transe e possessão');
   CIDList.add('F44.4 - Transtornos dissociativos motores');
   CIDList.add('F44.5 - Convulsões dissociativas');
   CIDList.add('F44.6 - Anestesia e perda sensorial dissociativas');
   CIDList.add('F44.6 - Transtorno dissociativo misto [de conversão]');
   CIDList.add('F45 - Transtornos somatoformes');
   CIDList.add('F45.0 - Transtorno de somatização');
   CIDList.add('F48 - Outros transtornos neuróticos');
   CIDList.add('F48.0 - Neurastenia');
   CIDList.add('F48.1 - Síndrome de despersonalização-desrealização');
   CIDList.add('F48.8 - Outros transtornos neuróticos especificados');
   CIDList.add('F48.9 - Transtorno neurótico, não especificado');
   CIDList.add('F50 - Transtornos da alimentação');
   CIDList.add('F50.0 - Anorexia nervosa');
   CIDList.add('F50.2 - Bulimia nervosa');
   CIDList.add('F51 - Transtornos não-orgânicos do sono devidos a fatores emocionais');
   CIDList.add('F51.0 - Insônia não-orgânica');
   CIDList.add('F51.1 - Hipersonia não-orgânica');
   CIDList.add('F51.2 - Transtorno do ciclo vigília-sono devido a fatores não-orgânicos');
   CIDList.add('F51.3 - Sonambulismo');
   CIDList.add('F51.4 - Terrores noturnos');
   CIDList.add('F51.5 - Pesadelos');
   CIDList.add('F52 - Disfunção sexual, não causada por transtorno ou doença orgânica');
   CIDList.add('F52.0 - Ausência ou perda do desejo sexual');
   CIDList.add('F52.1 - Aversão sexual e ausência de prazer sexual');
   CIDList.add('F52.2 - Falha de resposta genital Impotência psicogênica -');
   CIDList.add('F52.3 - Disfunção orgásmica Anorgasmia psicogênica -');
   CIDList.add('F52.4 - Ejaculação precoce');
   CIDList.add('F52.5 - Vaginismo não-orgânico');
   CIDList.add('F52.6 - Dispareunia não-orgânica');
   CIDList.add('F52.7 - Apetite sexual excessivo Ninfomania para mulheres, Satiríase para homens -');
   CIDList.add('F53 - Transtornos mentais e comportamentais associados ao puerpério, não classificados em outra parte');
   CIDList.add('F53.0 - Transtornos mentais e comportamentais leves associados ao puerpério não classificados em outra parte');
   CIDList.add('F53.1 - Transtornos mentais e comportamentais graves associados ao puerpério não classificados em outra parte');
   CIDList.add('F54 - Fatores psicológicos ou comportamentais associados a doença ou a transtornos classificados em outra parte');
   CIDList.add('F55 - Abuso de substâncias que não produzem dependência');
   CIDList.add('F59 - Síndromes comportamentais associados a transtornos das funções fisiológicas e a fatores físicos, não especificadas');
   CIDList.add('F60 - Transtorno de personalidade específico');
   CIDList.add('F60.0 - Transtorno de personalidade paranóide');
   CIDList.add('F60.1 - Transtorno de personalidade esquizóide');
   CIDList.add('F60.2 - Transtorno de personalidade dissocial sociopatia -');
   CIDList.add('F60.3 - Transtorno de personalidade emocionalmente instável');
   CIDList.add('F60.4 - Transtorno de personalidade histriônica');
   CIDList.add('F60.5 - Transtorno de personalidade anancástica');
   CIDList.add('F60.6 - Transtorno de personalidade esquiva');
   CIDList.add('F60.7 - Transtorno de personalidade dependente');
   CIDList.add('F60.8 - Outros Transtorno de personalidade específico');
   CIDList.add('F60.9 - Transtorno de personalidade, inespecífico ');
   CIDList.add('F61 - Misto e outros transtorno de personalidade');
   CIDList.add('F62 - Modificações duradouras da personalidade não atribuível a danos cerebrais e enfermidades');
   CIDList.add('F63 - Transtornos dos hábitos e dos impulsos');
   CIDList.add('F63.0 - Jogo patológico');
   CIDList.add('F63.1 - Piromania');
   CIDList.add('F63.2 - Roubo Patológico Cleptomania -');
   CIDList.add('F63.3 - Tricotilomania');
   CIDList.add('F64 - Transtorno de identidade de gênero');
   CIDList.add('F64.0 - Transexualismo');
   CIDList.add('F64.1 - Travestismo de duplo papel');
   CIDList.add('F64.2 - Transtorno de identidade de gênero infantil');
   CIDList.add('F65 - Transtornos da preferência sexual parafilia -');
   CIDList.add('F65.0 - Fetichismo');
   CIDList.add('F65.1 - Travestismo fetichista');
   CIDList.add('F65.2 - Exibicionismo');
   CIDList.add('F65.3 - Voyeurismo');
   CIDList.add('F65.4 - Pedofilia');
   CIDList.add('F65.5 - Sadomasoquismo');
   CIDList.add('F65.6 - Múltiplas distorções da preferência sexual');
   CIDList.add('F65.8 - Outras desordens da preferência sexual');
   CIDList.add('F66 - Transtornos psicológicos e comportamentais associados ao desenvolvimento e à sua orientação sexual');
   CIDList.add('F66.0 - Desordem da maturidade sexual');
   CIDList.add('F66.1 - Orientação sexual egodistônica');
   CIDList.add('F66.2 - Transtorno do relacionamento sexual');
   CIDList.add('F66.8 - Outros transtornos do desenvolvimento psicossexual');
   CIDList.add('F66.9 - Transtorno do desenvolvimento sexual, não especificado');
   CIDList.add('F68 - Outros transtornos da personalidade e do comportamento do adulto');
   CIDList.add('F68.0 - Sintomas físicos aumentados por fatores psicológicos');
   CIDList.add('F68.1 - Produção deliberada ou simulação de sintomas ou de incapacidades, físicas ou psicológicas transtorno factício');
   CIDList.add('F68.8 - Outros transtornos especificados da personalidade e do comportamento do adulto');
   CIDList.add('F69 - Transtorno da personalidade e do comportamento do adulto, não especificado');
   CIDList.add('F70 - Retardo mental leve');
   CIDList.add('F71 - Retardo mental moderado');
   CIDList.add('F72 - Retardo mental grave');
   CIDList.add('F73 - Retardo mental profundo');
   CIDList.add('F78 - Outro retardo mental');
   CIDList.add('F79 - Retardo mental não especificado');
   CIDList.add('F80 - Transtornos específicos do desenvolvimento da fala e da linguagem');
   CIDList.add('F80.0 - Transtorno específico da articulação da fala');
   CIDList.add('F80.1 - Transtorno expressivo de linguagem');
   CIDList.add('F80.2 - Transtorno receptivo da linguagem');
   CIDList.add('F80.3 - Afasia adquirida com epilepsia síndrome de Landau-Kleffner -');
   CIDList.add('F80.8 - Outros transtornos de desenvolvimento da fala ou da linguagem');
   CIDList.add('F80.9 - Transtorno não especificado do desenvolvimento da fala ou da linguagem ');
   CIDList.add('F81 - Transtornos específicos do desenvolvimento das habilidades escolares');
   CIDList.add('F81.0 - Transtorno específico de leitura');
   CIDList.add('F81.1 - Transtorno específico da soletração');
   CIDList.add('F81.2 - Transtorno específico da habilidade em aritmética');
   CIDList.add('F81.3 - Transtorno misto de habilidades escolares');
   CIDList.add('F81.8 - Outros transtornos do desenvolvimento das habilidades escolares');
   CIDList.add('F81.9 - Transtorno não especificado do desenvolvimento das habilidades escolares');
   CIDList.add('F82 - Transtorno específico do desenvolvimento motor');
   CIDList.add('F83 - Transtornos específicos misto do desenvolvimento');
   CIDList.add('F84 - Transtornos globais do desenvolvimento');
   CIDList.add('F84.0 - Autismo infantil');
   CIDList.add('F84.2 - Síndrome de Rett');
   CIDList.add('F84.4 - Transtorno com hipercinesia associada a retardo mental e a movimentos estereotipados');
   CIDList.add('F84.5 - Síndrome de Asperger');
   CIDList.add('F88 - Outros transtornos do desenvolvimento psicológico');
   CIDList.add('F89 - Transtorno do desenvolvimento psicológico não especificado');
   CIDList.add('F90 - Transtornos hipercinéticos');
   CIDList.add('F90.0 - Transtorno do déficit de atenção e hiperatividade');
   CIDList.add('F90.1 - Transtorno hipercinético de conduta');
   CIDList.add('F91 - Distúrbios de conduta');
   CIDList.add('F91.0 - Distúrbio de conduta restrito ao concaptiono familiar');
   CIDList.add('F91.1 - Distúrbio de conduta não-socializado');
   CIDList.add('F91.2 - Distúrbio de conduta do tipo socializado');
   CIDList.add('F91.3 - Distúrbio desafiador e de oposição');
   CIDList.add('F92 - Transtornos mistos de conduta e das emoções');
   CIDList.add('F92.0 - Distúrbio depressivo de conduta');
   CIDList.add('F93 - Transtornos emocionais com início especificamente na infância');
   CIDList.add('F93.0 - Transtorno ligado à angústia de separação');
   CIDList.add('F93.1 - Transtorno fóbico ansioso da infância');
   CIDList.add('F93.2 - Distúrbio de ansiedade social da infância');
   CIDList.add('F93.3 - Transtorno de rivalidade entre irmãos');
   CIDList.add('F94 - Transtornos do funcionamento social com início especificamente durante a infância ou a adolescência');
   CIDList.add('F94.0 - Mutismo eletivo');
   CIDList.add('F94.1 - Distúrbio reativo de vinculação da infância');
   CIDList.add('F94.2 - Transtorno de fixação da infância, com desinibição');
   CIDList.add('F95 - Tiques');
   CIDList.add('F95.0 - Tique transitório');
   CIDList.add('F95.1 - Tique motor ou vocal crônico');
   CIDList.add('F95.2 - Tiques vocais e motores múltiplos combinados Síndrome de Tourette -');
   CIDList.add('F98 - Outros transtornos comportamentais e emocionais com início habitualmente durante a infância ou a adolescência');
   CIDList.add('F98.0 - Enurese de origem não-orgânica');
   CIDList.add('F98.1 - Encoprese de origem não-orgânica');
   CIDList.add('F98.2 - Transtorno de alimentação na infância');
   CIDList.add('F98.3 - Pica do lactente ou da criança');
   CIDList.add('F98.4 - Estereotipias motoras ');
   CIDList.add('F98.5 - Gagueira tartamudez -');
   CIDList.add('F98.6 - Linguagem precipitada');
   CIDList.add('F98.8 - Outros transtornos comportamentais e emocionais especificados com início habitualmente na infância ou adolescência');
   CIDList.add('F98.9 - Transtornos comportamentais e emocionais não especificados com início habitualmente na infância ou adolescência');
   CIDList.add('F99.0 - Transtorno mental não especificado em outra parte');
   CIDList.add('Y98.0 - LUTO');

   CIDList.add('H00.0-Hordéolo e outras inflamações profundas das pálpebras');
   CIDList.add('H00.1-Calázio');
   CIDList.add('H01-Outras inflamações da pálpebra');
   CIDList.add('H01.0-Blefarite');
   CIDList.add('H01.1-Dermatoses não infecciosas da pálpebra');
   CIDList.add('H01.8-Outras inflamações especificadas da pálpebra');
   CIDList.add('H01.9-Inflamação não especificada da pálpebra');
   CIDList.add('H02-Outros transtornos da pálpebra');
   CIDList.add('H02.0-Entrópio e triquíase da pálpebra');
   CIDList.add('H02.1-Ectrópio da pálpebra');
   CIDList.add('H02.2-Lagoftalmo');
   CIDList.add('H02.3-Blefarocalásia');
   CIDList.add('H02.4-Ptose da pálpebra');
   CIDList.add('H02.5-Outros transtornos que afetam a função da pálpebra');
   CIDList.add('H02.6-Xantelasma da pálpebra');
   CIDList.add('H02.7-Outros transtornos degenerativos da pálpebra e da área periocular');
   CIDList.add('H02.8-Outros transtornos especificados das pálpebras');
   CIDList.add('H02.9-Transtorno não especificado da pálpebra');
   CIDList.add('H03-*Transtornos da pálpebra em doenças classificadas em outras partes');
   CIDList.add('H03.0-*Infestação parasitária da pálpebra em doenças classificadas em outra parte');
   CIDList.add('H03.1-*Comprometimento da pálpebra em outras doenças infecciosas classificadas em outra parte');
   CIDList.add('H03.8-*Comprometimento da pálpebra em outras doenças classificadas em outras partes');
   CIDList.add('H04-Transtornos do aparelho lacrimal');
   CIDList.add('H04.0-Dacrioadenite');
   CIDList.add('H04.1-Outros transtornos da glândula lacrimal');
   CIDList.add('H04.2-Epífora');
   CIDList.add('H04.3-Inflamação aguda e não especificada dos canais lacrimais');
   CIDList.add('H04.4-Inflamação crônica dos canais lacrimais');
   CIDList.add('H04.5-Estenose e insuficiência dos canais lacrimais');
   CIDList.add('H04.6-Outras alterações nos canais lacrimais');
   CIDList.add('H04.8-Outros transtornos do aparelho lacrimal');
   CIDList.add('H04.9-Transtorno não especificado do aparelho lacrimal');
   CIDList.add('H05-Transtornos da órbita');
   CIDList.add('H05.0-Inflamação aguda da órbita');
   CIDList.add('H05.1-Transtornos inflamatórios crônicos da órbita');
   CIDList.add('H05.2-Afecções exoftálmicas');
   CIDList.add('H05.3-Deformidade da órbita');
   CIDList.add('H05.4-Enoftalmia');
   CIDList.add('H05.5-Corpo estranho antigo-retido conseqüente a ferimento perfurante da órbita');
   CIDList.add('H05.8-Outros transtornos da órbita');
   CIDList.add('H05.9-Transtorno não especificado da órbita');
   CIDList.add('H06-*Transtornos do aparelho lacrimal e da órbita em doenças classificadas em outra parte');
   CIDList.add('H06.0-*Transtornos do aparelho lacrimal em doenças classificadas em outra parte');
   CIDList.add('H06.1-*Infestação parasitária da órbita em doenças classificadas em outra parte');
   CIDList.add('H06.2-*Exoftalmo distireoídeo');
   CIDList.add('H06.3-*Outros transtornos da órbita em doenças classificadas em outra parte');
   CIDList.add('H10-H13-Transtornos da conjuntiva');
   CIDList.add('H10-Conjuntivite');
   CIDList.add('H10.0-Conjuntivite mucopurulenta');
   CIDList.add('H10.1-Conjuntivite aguda atópica');
   CIDList.add('H10.2-Outras conjuntivites agudas');
   CIDList.add('H10.3-Conjuntivite aguda não especificada');
   CIDList.add('H10.4-Conjuntivite crônica');
   CIDList.add('H10.5-Blefaroconjuntivite');
   CIDList.add('H10.8-Outras conjuntivites');
   CIDList.add('H10.9-Conjuntivite não especificada');
   CIDList.add('H11-Outros transtornos da conjuntiva');
   CIDList.add('H11.0-Pterígio');
   CIDList.add('H11.1-Degenerações e depósitos da conjuntiva');
   CIDList.add('H11.2-Cicatrizes da conjuntiva');
   CIDList.add('H11.3-Hemorragia conjuntival');
   CIDList.add('H11.4-Outros transtornos vasculares e cistos conjuntivais');
   CIDList.add('H11.8-Outros transtornos especificados da conjuntiva');
   CIDList.add('H11.9-Transtorno não especificado da conjuntiva');
   CIDList.add('H13-*Transtornos da conjuntiva em doenças classificadas em outra parte');
   CIDList.add('H13.0-*Infestação por filárias na conjuntiva');
   CIDList.add('H13.1-*Conjuntivite em doenças infecciosas e parasitárias classificadas em outra parte');
   CIDList.add('H13.2-*Conjuntivite em outras doenças classificadas em outra parte');
   CIDList.add('H13.3-*Penfigóide ocular');
   CIDList.add('H13.8-*Outros transtornos da conjuntiva em doença classificadas em outra parte');
   CIDList.add('H15-Transtornos da esclera');
   CIDList.add('H15.0-Esclerite');
   CIDList.add('H15.1-Episclerite');
   CIDList.add('H16-Ceratite');
   CIDList.add('H16.0-Úlcera da córnea');
   CIDList.add('H16.1-Outras ceratites superficiais sem conjuntivite');
   CIDList.add('H16.2-Ceratoconjuntivite');
   CIDList.add('H16.3-Ceratite intersticial e profunda');
   CIDList.add('H16.4-Neovascularização da córnea');
   CIDList.add('H17-Cicatrizes e opacidades da córnea');
   CIDList.add('H18-Outros transtornos da córnea');
   CIDList.add('H18.0-Pigmentações e depósitos na córnea');
   CIDList.add('H18.1-Ceratopatia bolhosa');
   CIDList.add('H18.2-Outros edemas da córnea');
   CIDList.add('H18.3-Alterações nas membranas da córnea');
   CIDList.add('H18.4-Degeneração da córnea');
   CIDList.add('H18.5-Distrofias hereditárias da córnea');
   CIDList.add('H18.6-Ceratocone');
   CIDList.add('H18.7-Outras deformidades da córnea');
   CIDList.add('H18.8-Outros transtornos especificados da córnea');
   CIDList.add('H18.9-Transtorno não-especificado da córnea');
   CIDList.add('H19-Transtornos da esclera e da córnea em doenças classificadas em outra part ');
   CIDList.add('H19.0-Esclerite e episclerite em doenças classificadas em outra parte');
   CIDList.add('H19.1-Ceratite e ceratoconjuntivite pelo vírus do herpes simples');
   CIDList.add('H19.2-Ceratite e ceratoconjuntivite em outras doenças infecciosas e parasitárias');
   CIDList.add('H19.3-Ceratite e ceratoconjuntivite em doenças classificadas em outra parte');
   CIDList.add('H19.8-Outros transtornos da esclera e da córnea em doenças classificadas em outra parte');
   CIDList.add('H20-H22-Transtornos da íris e do corpo ciliar');
   CIDList.add('H20-Iridociclite');
   CIDList.add('H20.0-Iridociclite aguda e subaguda');
   CIDList.add('H21-Outros transtornos da íris e do corpo ciliar');
   CIDList.add('H21.0-Hifema');
   CIDList.add('H21.1-Outros transtornos vasculares da íris e do corpo ciliar');
   CIDList.add('H21.2-Degeneração da íris e do corpo ciliar');
   CIDList.add('Heterocromia da íris');
   CIDList.add('H21.3-Cisto da íris, do corpo ciliar ou da câmara anterior');
   CIDList.add('H21.4-Membranas pupilares');
   CIDList.add('H25-H28-Transtornos do cristalino');
   CIDList.add('H25-Catarata senil ');
   CIDList.add('H26-Outras cataratas');
   CIDList.add('H27-Outros transtornos do cristalino');
   CIDList.add('H27.0-Afacia');
   CIDList.add('H27.1-Deslocamento do cristalino');
   CIDList.add('H28-Catarata e outros transtornos do cristalino em doenças classificadas em outra parte');
end;

procedure TTabelaCID.SetCodigo(const Value: Integer);
begin
  FCodigo := Value;
end;

procedure TTabelaCID.SetDescricao(const Value: string);
begin
  FDescricao := Value;
end;

end.

